### ISSUE TITLE
Not resumable after network intervention for couple of minutes 

### ISSUE THREAD

**Issue by Bhasheyam** [tus/tus-resumable-upload-protocol#133]
Hi,

I used JAVA Client in rest endpoint to upload the file. Created a manual network intervention to check the resumable upload. But i am getting exceptions and upload stops. 

 Client : https://github.com/tus/tus-java-client/tree/master/example/src/main/java/io/tus/java/example

is there anything i am missing on the client config to make reasumable.

Thanks
Bhasheyam

**Comment by taufiquealam007** [comment]
HI,

The resumable part is working fine till 2 minutes but after 2 minutes when network is up then it is giving this exception

java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at io.tus.java.client.TusClient.beginOrResumeUploadFromURL(TusClient.java:223)
	at io.tus.java.client.TusClient.resumeUpload(TusClient.java:198)
	at io.tus.java.client.TusClient.resumeOrCreateUpload(TusClient.java:251)
	at io.tus.java.example.Main$1.makeAttempt(Main.java:69)
	at io.tus.java.client.TusExecutor.makeAttempts(TusExecutor.java:85)
	at io.tus.java.example.Main.main(Main.java:93)

**Comment by Bhasheyam** [comment]
https://hangouts.google.com/call/8TfI2HQxQJzBrS54-1A9AAEE

**Comment by Acconut** [comment]
These issues should be filed in the corresponding repositories, e.g. https://github.com/tus/tus-java-client
